default_language_version:
    python: python3.7
exclude: vendor
repos:
    - repo: https://github.com/asottile/seed-isort-config
      rev: v1.9.4
      hooks:
          - id: seed-isort-config
            args: [--exclude=vendor]
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
          - id: isort
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: flake8
            files: ^republic-ml/
          - id: end-of-file-fixer
          - id: trailing-whitespace